// Code generated by go-swagger; DO NOT EDIT.

package your_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/suzuken/go-misc/grpc-gateway-example/models"
)

// NewEchoParams creates a new EchoParams object
// with the default values initialized.
func NewEchoParams() *EchoParams {
	var ()
	return &EchoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEchoParamsWithTimeout creates a new EchoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEchoParamsWithTimeout(timeout time.Duration) *EchoParams {
	var ()
	return &EchoParams{

		timeout: timeout,
	}
}

// NewEchoParamsWithContext creates a new EchoParams object
// with the default values initialized, and the ability to set a context for a request
func NewEchoParamsWithContext(ctx context.Context) *EchoParams {
	var ()
	return &EchoParams{

		Context: ctx,
	}
}

// NewEchoParamsWithHTTPClient creates a new EchoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEchoParamsWithHTTPClient(client *http.Client) *EchoParams {
	var ()
	return &EchoParams{
		HTTPClient: client,
	}
}

/*EchoParams contains all the parameters to send to the API endpoint
for the echo operation typically these are written to a http.Request
*/
type EchoParams struct {

	/*Body*/
	Body *models.ExampleStringMessage

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the echo params
func (o *EchoParams) WithTimeout(timeout time.Duration) *EchoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the echo params
func (o *EchoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the echo params
func (o *EchoParams) WithContext(ctx context.Context) *EchoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the echo params
func (o *EchoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the echo params
func (o *EchoParams) WithHTTPClient(client *http.Client) *EchoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the echo params
func (o *EchoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the echo params
func (o *EchoParams) WithBody(body *models.ExampleStringMessage) *EchoParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the echo params
func (o *EchoParams) SetBody(body *models.ExampleStringMessage) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *EchoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
