# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_service.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "example.StringMessage" do
    optional :value, :string, 1
  end
end

module Example
  StringMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.StringMessage").msgclass
end
