// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi my_service.proto

    Schemes:
      http
      https
    Host: localhost
    BasePath: /
    Version: version not set

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
