/**
 * my_service.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExampleStringMessage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ExampleStringMessage'));
  } else {
    // Browser globals (root is window)
    if (!root.MyServiceproto) {
      root.MyServiceproto = {};
    }
    root.MyServiceproto.YourServiceApi = factory(root.MyServiceproto.ApiClient, root.MyServiceproto.ExampleStringMessage);
  }
}(this, function(ApiClient, ExampleStringMessage) {
  'use strict';

  /**
   * YourService service.
   * @module api/YourServiceApi
   * @version version not set
   */

  /**
   * Constructs a new YourServiceApi. 
   * @alias module:api/YourServiceApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the echo operation.
     * @callback module:api/YourServiceApi~echoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExampleStringMessage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/ExampleStringMessage} body 
     * @param {module:api/YourServiceApi~echoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExampleStringMessage}
     */
    this.echo = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling echo");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ExampleStringMessage;

      return this.apiClient.callApi(
        '/v1/example/echo', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
