/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * my_service.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface ExampleStringMessage
 */
export interface ExampleStringMessage {
    /**
     * 
     * @type {string}
     * @memberof ExampleStringMessage
     */
    value?: string;
}


/**
 * YourServiceApi - fetch parameter creator
 * @export
 */
export const YourServiceApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ExampleStringMessage} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        echo(body: ExampleStringMessage, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling echo.');
            }
            const localVarPath = `/v1/example/echo`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"ExampleStringMessage" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * YourServiceApi - functional programming interface
 * @export
 */
export const YourServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ExampleStringMessage} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        echo(body: ExampleStringMessage, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<ExampleStringMessage> {
            const localVarFetchArgs = YourServiceApiFetchParamCreator(configuration).echo(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * YourServiceApi - factory interface
 * @export
 */
export const YourServiceApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {ExampleStringMessage} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        echo(body: ExampleStringMessage, options?: any) {
            return YourServiceApiFp(configuration).echo(body, options)(fetch, basePath);
        },
    };
};

/**
 * YourServiceApi - object-oriented interface
 * @export
 * @class YourServiceApi
 * @extends {BaseAPI}
 */
export class YourServiceApi extends BaseAPI {
    /**
     * 
     * @param {} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof YourServiceApi
     */
    public echo(body: ExampleStringMessage, options?: any) {
        return YourServiceApiFp(this.configuration).echo(body, options)(this.fetch, this.basePath);
    }

}

